name: RqueR Blog
description: Análisis y visualización de opendata con R
url: rquer.github.io
markdown: redcarpet
#markdown: markdown
#markdown:
#  input: GFM
highlighter: pygments
#permalink: /:title
#paginate: 10
paginate_path: /blog/page/:num
encoding: utf-8
gems:
  - jekyll-feed